#!/usr/bin/env bash
# deploy_macos.sh — build Musil for macOS and package it.
#
#   ./deploy_macos.sh               Release, static, universal (arm64 + x86_64), in build-dist/
#   ./deploy_macos.sh --clean       delete build-dist/ first (FLTK rebuilt fat from scratch)
#   ./deploy_macos.sh --no-build    just package what is in build-dist/
#   ./deploy_macos.sh --dmg         also make dist/Musil-<version>.dmg
#
#   ARCHS=arm64 ./deploy_macos.sh   single-arch build (faster)
#
# Produces
#   dist/Musil.app                  the IDE as an application, with icon (docs/icon.png or .jpg),
#                                   the .mu libraries, help.txt and the manual in Resources/
#   dist/musil                      the command-line interpreter
#   dist/musil-ide                  the IDE as a plain binary (finds lib/ next to it)
#   dist/lib/                       the .mu libraries and help.txt, to copy into ~/.musil for the CLI
#   dist/musil_manual.pdf           the manual
#   dist/Musil-<version>-macos.zip  all of the above
set -euo pipefail
cd "$(dirname "$0")"

FLAG="${1:-}"
APP_NAME="Musil"
BUNDLE_ID="com.carminecella.musil"
VERSION="$(sed -n 's/.*MUSIL_VERSION "\(.*\)".*/\1/p' src/core.h | head -1)"
BUILD_DIR="build-dist"
ARCHS="${ARCHS:-arm64;x86_64}"
MIN_MACOS="${MIN_MACOS:-12.0}"
DIST="dist"
APP="$DIST/$APP_NAME.app"

[[ "$(uname)" == "Darwin" ]] || { echo "This script builds a macOS bundle; run it on a Mac." >&2; exit 1; }

# --- 0. documentation: help.txt is regenerated by the configure; the PDF is built when pdflatex exists
if command -v pdflatex >/dev/null && [[ ! -f docs/musil_manual.pdf ]]; then
    echo "==> Building the manual"
    ( cd docs && python3 ../tools/gendoc.py >/dev/null && pdflatex -interaction=nonstopmode musil_manual.tex >/dev/null && pdflatex -interaction=nonstopmode musil_manual.tex >/dev/null && rm -f *.aux *.log *.out *.toc ) || echo "    (manual not built)"
fi

# --- 1. build -----------------------------------------------------------------------
[[ "$FLAG" == "--clean" ]] && { echo "==> Removing $BUILD_DIR"; rm -rf "$BUILD_DIR"; }
if [[ "$FLAG" != "--no-build" ]]; then
    echo "==> Configuring (Release, static, archs: $ARCHS, macOS >= $MIN_MACOS)"
    cmake -B "$BUILD_DIR" \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_OSX_ARCHITECTURES="$ARCHS" \
        -DCMAKE_OSX_DEPLOYMENT_TARGET="$MIN_MACOS" \
        -DBUILD_SHARED_LIBS=OFF -DMUSIL_TESTS=OFF -DMUSIL_READLINE=OFF
    echo "==> Building musil-ide and musil"
    cmake --build "$BUILD_DIR" -j --target musil-ide musil
fi
IDE="$BUILD_DIR/musil-ide"
CLI="$BUILD_DIR/musil"
for BIN in "$IDE" "$CLI"; do
    [[ -x "$BIN" ]] || { echo "Binary $BIN not found. Build first." >&2; exit 1; }
    echo "==> Binary: $(lipo -info "$BIN" 2>/dev/null || file "$BIN")"
    for arch in ${ARCHS//;/ }; do
        lipo "$BIN" -verify_arch "$arch" 2>/dev/null || { echo "ERROR: $BIN lacks $arch. Run: $0 --clean" >&2; exit 1; }
    done
    if otool -L "$BIN" | grep -qv -e '/System/Library' -e '/usr/lib' -e "$BIN"; then
        echo "    WARNING: $BIN links libraries outside the system; it may not run on other Macs:" >&2
        otool -L "$BIN" | grep -v -e '/System/Library' -e '/usr/lib' -e "$BIN" >&2
    fi
done
FLTK_A=$(find "$BUILD_DIR/_deps" -name 'libfltk.a' 2>/dev/null | head -1)
[[ -n "$FLTK_A" ]] && echo "==> FLTK: $(lipo -info "$FLTK_A" 2>/dev/null)"

# --- 2. bundle skeleton --------------------------------------------------------------
# Only the IDE goes in MacOS/: a case-insensitive file system cannot hold "Musil" and
# "musil" side by side, so the CLI lives in dist/ next to the app.
echo "==> Creating $APP"
rm -rf "$DIST"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources/lib" "$DIST/lib"
cp "$IDE" "$APP/Contents/MacOS/$APP_NAME"
chmod +x "$APP/Contents/MacOS/$APP_NAME"
cp "$CLI" "$DIST/musil"
cp "$IDE" "$DIST/musil-ide"
strip "$DIST/musil" "$DIST/musil-ide" 2>/dev/null || true

# --- 3. resources: font, libraries, help, manual -------------------------------------------
echo "==> Copying resources"
cp src/*.mu src/help.txt "$APP/Contents/Resources/lib/"
cp src/*.mu src/help.txt "$DIST/lib/"
[[ -f docs/musil_manual.pdf ]] && cp docs/musil_manual.pdf "$APP/Contents/Resources/" && cp docs/musil_manual.pdf "$DIST/"
cp README.md LICENSE.md "$DIST/"

# --- 4. icon (docs/icon.png or docs/icon.jpg -> .icns) --------------------------------------
ICON_SRC=""
for f in docs/icon.png docs/icon.jpg docs/icon.jpeg; do [[ -f "$f" ]] && { ICON_SRC="$f"; break; }; done
if [[ -n "$ICON_SRC" ]]; then
    echo "==> Generating icon"
    ICONSET="$DIST/$APP_NAME.iconset"
    rm -rf "$ICONSET"; mkdir -p "$ICONSET"
    for size in 16 32 64 128 256 512; do
        sips -z $size $size "$ICON_SRC" --out "$ICONSET/icon_${size}x${size}.png" >/dev/null
        dbl=$((size * 2))
        sips -z $dbl $dbl "$ICON_SRC" --out "$ICONSET/icon_${size}x${size}@2x.png" >/dev/null
    done
    iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/$APP_NAME.icns"
    rm -rf "$ICONSET"
else
    echo "    (no docs/icon.png or docs/icon.jpg, skipping icon)"
fi

# --- 5. Info.plist ------------------------------------------------------------------------
cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>               <string>$APP_NAME</string>
    <key>CFBundleDisplayName</key>        <string>$APP_NAME</string>
    <key>CFBundleIdentifier</key>         <string>$BUNDLE_ID</string>
    <key>CFBundleVersion</key>            <string>$VERSION</string>
    <key>CFBundleShortVersionString</key> <string>$VERSION</string>
    <key>CFBundleExecutable</key>         <string>$APP_NAME</string>
    <key>CFBundleIconFile</key>           <string>$APP_NAME</string>
    <key>CFBundlePackageType</key>        <string>APPL</string>
    <key>LSMinimumSystemVersion</key>     <string>$MIN_MACOS</string>
    <key>NSHighResolutionCapable</key>    <true/>
    <key>NSMicrophoneUsageDescription</key> <string>Musil can analyse sound from the microphone.</string>
    <key>NSPrincipalClass</key>           <string>NSApplication</string>
    <key>CFBundleDocumentTypes</key>
    <array><dict>
        <key>CFBundleTypeName</key>       <string>Musil source</string>
        <key>CFBundleTypeExtensions</key> <array><string>mu</string></array>
        <key>CFBundleTypeRole</key>       <string>Viewer</string>
    </dict></array>
</dict>
</plist>
PLIST

# --- 6. ad-hoc signature (required on Apple Silicon to launch at all) --------------------------
echo "==> Signing (ad-hoc)"
codesign --force --deep --sign - "$APP"
codesign --force --sign - "$DIST/musil" "$DIST/musil-ide"

# --- 6b. the VS Code extension, as a .vsix when npx is available ------------------------------
if command -v npx >/dev/null; then
    echo "==> VS Code extension"
    ( cd editors/vscode/musil && npx --yes @vscode/vsce package --allow-missing-repository -o "../../../$DIST/musil-$VERSION.vsix" >/dev/null 2>&1 ) || echo "    (vsce failed; skipping the .vsix)"
fi

# --- 7. zip for sending ---------------------------------------------------------------------
echo "==> Zipping"
( cd "$DIST" && rm -f "$APP_NAME-$VERSION-macos.zip" && ditto -c -k --keepParent --norsrc "$APP_NAME.app" "$APP_NAME-$VERSION-macos.zip" \
  && zip -qr "$APP_NAME-$VERSION-macos.zip" musil musil-ide lib README.md LICENSE.md $( [[ -f musil_manual.pdf ]] && echo musil_manual.pdf ) )

if [[ "$FLAG" == "--dmg" ]]; then
    echo "==> DMG"
    rm -f "$DIST/$APP_NAME-$VERSION.dmg"
    hdiutil create -volname "$APP_NAME" -srcfolder "$APP" -ov -format UDZO "$DIST/$APP_NAME-$VERSION.dmg" >/dev/null
fi

echo
echo "Done: $APP, $DIST/musil, $DIST/musil-ide, $DIST/lib, $DIST/musil_manual.pdf  and  $DIST/$APP_NAME-$VERSION-macos.zip"
echo "Recipients: unzip, then right-click Musil.app -> Open (first launch only, it is not notarized)."
echo "The CLI: copy musil somewhere in the PATH and lib/* into ~/.musil."
