#!/usr/bin/env bash
# deploy_linux.sh — build a redistributable Linux folder for Musil.
#
#   ./deploy_linux.sh            Release, static raylib, into build-dist-linux/
#   ./deploy_linux.sh --clean    rebuild from scratch
#
# Produces dist/musil-<version>-linux/ (Musil the Listener, musil the CLI, lib/, the manual,
# run.sh) and dist/musil-<version>-linux.tar.gz. The binaries still need the system's
# OpenGL, X11 and ALSA libraries at run time, which every desktop Linux has.
set -euo pipefail
cd "$(dirname "$0")"

[[ "$(uname)" == "Linux" ]] || { echo "This script packages a Linux build; run it on Linux." >&2; exit 1; }
VERSION="$(sed -n 's/.*MUSIL_VERSION "\(.*\)".*/\1/p' src/core.h | head -1)"
BUILD_DIR="build-dist-linux"
OUT="dist/musil-$VERSION-linux"

# help.txt is regenerated by the configure; the PDF is built when pdflatex exists
if command -v pdflatex >/dev/null && [[ ! -f docs/musil_manual.pdf ]]; then
    ( cd docs && python3 ../tools/gendoc.py >/dev/null && pdflatex -interaction=nonstopmode musil_manual.tex >/dev/null && pdflatex -interaction=nonstopmode musil_manual.tex >/dev/null && rm -f *.aux *.log *.out *.toc ) || echo "    (manual not built)"
fi

[[ "${1:-}" == "--clean" ]] && rm -rf "$BUILD_DIR"
echo "==> Configuring (Release, static)"
cmake -B "$BUILD_DIR" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DMUSIL_TESTS=OFF -DMUSIL_READLINE=OFF
echo "==> Building"
cmake --build "$BUILD_DIR" -j --target musil-listener musil
for BIN in "$BUILD_DIR/musil-listener" "$BUILD_DIR/musil"; do
    [[ -x "$BIN" ]] || { echo "Binary $BIN not found." >&2; exit 1; }
    echo "==> Runtime libraries of $BIN:"; ldd "$BIN" | sed 's/^/    /'
done

echo "==> Collecting into $OUT"
rm -rf "$OUT"; mkdir -p "$OUT/lib" "$OUT/assets"
cp "$BUILD_DIR/musil-listener" "$OUT/Musil"
cp "$BUILD_DIR/musil" "$OUT/musil"
strip "$OUT/Musil" "$OUT/musil" 2>/dev/null || true
cp listener/assets/JetBrainsMono-Regular.ttf listener/assets/JetBrainsMono-OFL.txt "$OUT/assets/"
cp src/*.mu src/help.txt "$OUT/lib/"
[[ -f docs/musil_manual.pdf ]] && cp docs/musil_manual.pdf "$OUT/"
cp README.md LICENSE.md "$OUT/"
cat > "$OUT/run.sh" <<RUN
#!/usr/bin/env bash
# the Listener finds lib/ and assets/ next to itself; the CLI needs MUSIL_PATH or ~/.musil
cd "\$(dirname "\$0")" && MUSIL_PATH="\$PWD/lib" ./Musil "\$@"
RUN
chmod +x "$OUT/run.sh"

( cd dist && rm -f "musil-$VERSION-linux.tar.gz" && tar -czf "musil-$VERSION-linux.tar.gz" "musil-$VERSION-linux" )
du -sh "$OUT" "dist/musil-$VERSION-linux.tar.gz" | sed 's/^/    /'
echo
echo "Done: $OUT  and  dist/musil-$VERSION-linux.tar.gz   (recipients: extract, ./run.sh; the CLI: ./musil with MUSIL_PATH=lib)"
