#!/usr/bin/env python3
"""gendoc.py — the documentation comes from the source.

Every library function is documented by the comment that precedes it, in one format:

    // (name args) description                      in a .h file
    # (name args) description                       in a .mu file

A line may name several forms that share the description ("(sin x) (cos x) ..."),
and continuation lines that start with the same comment marker and an indent (or
that do not start with "(") extend the description. This script collects them into

    src/help.txt              read by (help name) at run time
    docs/generated/<lib>.tex  the function reference of each library, included by the manual

Run it after editing any library: python3 tools/gendoc.py
"""
import re, sys, os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LIBS = [("core", ["src/core.h"]), ("std", ["src/std.h", "src/std.mu"]), ("system", ["src/system.h", "src/system.mu"]),
        ("scientific", ["src/scientific.h", "src/scientific.mu"]), ("signals", ["src/signals.h", "src/signals.mu"]),
        ("live", ["src/live.h", "src/live.mu"]), ("plot", ["src/plot.h", "src/plot.mu"])]
FORM = re.compile(r"^\(([^\s()]+)[^)]*\)")

REG = re.compile(r'(?:i\.def\(|\ba\(|\{)\s*"([^"]+)"')          # names registered in a .h file: i.def("x"), a("x"), {"x", fn}
DEF = re.compile(r"^function\s+([^\s()]+)", re.M)           # names defined in a .mu file

def entries(path):
    """Yield (names, signature-line, [description lines]) for one file: only comment blocks
    whose forms name something the file actually registers or defines count as documentation."""
    text_all = path.read_text()
    marker = "#" if path.suffix == ".mu" else "//"
    known = set(DEF.findall(text_all)) if path.suffix == ".mu" else set(REG.findall(text_all))
    out, block = [], None
    for raw in text_all.splitlines():
        line = raw.strip()
        if not line.startswith(marker):
            if block: out.append(block); block = None
            continue
        text = line[len(marker):].strip()
        indented = raw.lstrip()[len(marker):].startswith("  ") or raw.lstrip()[len(marker):].startswith("\t")
        if block and indented:
            block[2].append(text)
        elif text.startswith("("):
            if block: out.append(block)
            names, sig, rest = [], [], text
            while True:
                m = FORM.match(rest)
                if not m or m.group(1) not in known: break      # a form naming something else is description
                names.append(m.group(1)); sig.append(rest[:m.end()]); rest = rest[m.end():].strip()
            desc = rest.lstrip(":").strip()
            block = (names, "  ".join(sig), [desc] if desc else [])
        else:
            if block: out.append(block); block = None
    if block: out.append(block)
    return [(n, sig, d) for n, sig, d in out if n]

def tex(s):
    return s.replace("\\", "\\textbackslash{}").replace("&", "\\&").replace("%", "\\%").replace("$", "\\$").replace("#", "\\#").replace("_", "\\_").replace("{", "\\{").replace("}", "\\}").replace("~", "\\textasciitilde{}").replace("^", "\\^{}").replace("<", "\\textless{}").replace(">", "\\textgreater{}")

help_lines, total = [], 0
(ROOT / "docs/generated").mkdir(parents=True, exist_ok=True)
for lib, files in LIBS:
    tex_parts = ["% generated by tools/gendoc.py from the doc comments in src/; do not edit\n"]
    for f in files:
        p = ROOT / f
        if not p.exists(): continue
        for names, sig, desc in entries(p):
            if not names: continue
            total += 1
            help_lines.append("#" + " ".join(names))
            help_lines.append("  " + sig)
            for d in desc: help_lines.append("  " + d)
            tex_parts.append("\\fn{%s}{%s}\n" % (tex(sig), tex(" ".join(desc))))
    (ROOT / ("docs/generated/%s.tex" % lib)).write_text("".join(tex_parts))
(ROOT / "src/help.txt").write_text("# help.txt — generated by tools/gendoc.py from the doc comments in src/; do not edit\n" + "\n".join(help_lines) + "\n")

# the VS Code grammar: special forms, then every documented name, as a TextMate grammar
import json
names = []
for l in help_lines:
    if l.startswith("#"): names.extend(l[1:].split())
special = ["var", "set", "function", "return", "if", "while", "for", "break", "continue", "try", "catch", "do", "quote", "expr", "eval", "apply", "load", "help", "and", "or", "not"]
builtins = sorted(set(n for n in names if n not in special and re.match(r"^[A-Za-z][A-Za-z0-9\-?!>]*$", n)), key=len, reverse=True)
def alt(ws): return "|".join(re.escape(w) for w in ws)
grammar = {
    "$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
    "name": "Musil", "scopeName": "source.musil",
    "patterns": [
        {"name": "comment.line.number-sign.musil", "match": "#.*$"},
        {"name": "string.quoted.double.musil", "begin": "\"", "end": "\"", "patterns": [{"name": "constant.character.escape.musil", "match": "\\\\."}]},
        {"name": "constant.numeric.musil", "match": "(?<![A-Za-z0-9\\-])-?[0-9]+(\\.[0-9]+)?([eE][-+]?[0-9]+)?(?![A-Za-z0-9\\-])"},
        {"name": "constant.language.musil", "match": "(?<![A-Za-z0-9\\-])(nil|true|false|pi|inf|tau|euler|version)(?![A-Za-z0-9\\-?!>])"},
        {"name": "keyword.control.musil", "match": "(?<![A-Za-z0-9\\-])(" + alt(special) + ")(?![A-Za-z0-9\\-?!>])"},
        {"name": "entity.name.function.musil", "match": "(?<=function\\s)[A-Za-z][A-Za-z0-9\\-?!>]*"},
        {"name": "variable.other.constant.musil", "match": "'[A-Za-z][A-Za-z0-9\\-?!>]*"},
        {"name": "support.function.musil", "match": "(?<![A-Za-z0-9\\-?!>])(" + alt(builtins) + ")(?![A-Za-z0-9\\-?!>])"},
        {"name": "keyword.operator.musil", "match": "(?<=[\\s(])([-+*/]|<=|>=|==|!=|<|>|&&|\\|\\|)(?=[\\s)])"}
    ]
}
gpath = ROOT / "editors/vscode/musil/syntaxes/musil.tmLanguage.json"
if gpath.parent.exists(): gpath.write_text(json.dumps(grammar, indent=2) + "\n")
print("gendoc: %d entries -> src/help.txt, docs/generated/<library>.tex, the VS Code grammar (%d names)" % (total, len(builtins)))
