# uninstall.cmake — remove every file recorded in install_manifest.txt by the
# last `cmake --install`, then the directories this project created if they
# are now empty (include/musil, include/musil/system, ~/.musil).
if(NOT EXISTS "${MANIFEST}")
  message(FATAL_ERROR "no install manifest at ${MANIFEST}: nothing was installed from this build directory")
endif()
file(STRINGS "${MANIFEST}" files)
set(dirs "")
foreach(f ${files})
  if(EXISTS "${f}" OR IS_SYMLINK "${f}")
    message(STATUS "removing ${f}")
    file(REMOVE "${f}")
  else()
    message(STATUS "already gone: ${f}")
  endif()
  get_filename_component(d "${f}" DIRECTORY)
  list(APPEND dirs "${d}")
endforeach()
list(REMOVE_DUPLICATES dirs)
# deepest first, so include/musil/system goes before include/musil
list(SORT dirs ORDER DESCENDING)
foreach(d ${dirs})
  get_filename_component(name "${d}" NAME)
  if(name STREQUAL "musil" OR name STREQUAL "system" OR name STREQUAL ".musil")
    file(GLOB left "${d}/*")
    if(NOT left)
      message(STATUS "removing empty directory ${d}")
      file(REMOVE_RECURSE "${d}")
    endif()
  endif()
endforeach()
file(REMOVE "${MANIFEST}")
